### ISSUE TITLE
Why even accept a block?

### ISSUE THREAD

**Issue by tobyink** [robrwo/PerlX-Let#3]
Why this syntax?

```
let $x = 1 {
   ...;
}
```

You could make `let` behave more like `my`, `our`, and `state` using this syntax:

```
{
   let $x = 1;
   ...;
}
```

This would also make implementation a little easier because it essentially just becomes `s/let/Const::Fast::const my/g`.

**Comment by robrwo** [comment]
That's a good point, and in hindsight, I probably should have done something like that. 

But the implementation does a bit more than that: it checks the value, and if the value does not contain sigils, it will use a state variable where appropriate. (Some informal benchmarks show that using state variables is significantly faster in some circumstances, since it doesn't need to set the readonly flags for anything more complex than scalars every time.)

Since something like
```perl
foreach (1..2) {
  const state $x => { a => { c => 1 }, b => 2  };
  ...
}
```

does not work after the first iteration, it needs to do a bit more work.

I'd like to be able to do something with attributes like
```perl
{
  state $x:const = 1;
}
```
but I think that may require changes to Perl internals.

**Comment by tobyink** [comment]
`state` will be faster than `my` in some circumstances because it means that the memory for the variable doesn't need to be allocated and freed each time it's encountered. However, it's potentially a (probably small) waste of memory because it means that the memory *won't* be freed until the process ends.

**Comment by robrwo** [comment]
I realise that. I use state for speed, but I think the trade-off needs to be documented, as well as the implicit effect of enabling the state feature.

**Comment by robrwo** [comment]
I've updated the documentation in v0.2.6
